name: CI Voll Med
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: configure JDK 17 #configura java to run unit tests
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: configure docker-compose
        run: |
          sudo rm /usr/local/bin/docker-compose
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: run docker-compose
        run: docker compose up -d

      - name: execute unit tests
        run: mvn -B verify
